# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            William Donaldson
tagline:          'For the love of radio.'
description:      'For the love of radio.'
url:              http://williamdonaldson.me
baseurl:          /

timezone:         America/New_York

author:
  name:           'William Donaldson'
  url:            http://williamdonaldson.me

paginate:         5
paginate_path:    "posts/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wonaldson/williamdonaldson.me

# Collections
collections:
 audio:
  layout: item
 code:
  layout: item
 radio:
  layout: item
 videos:
  layout: item

# Social links
social:
  facebook: https://facebook.com/wonaldson
  twitter: https://twitter.com/wonaldson
  linkedin: https://linkedin.com/in/wonaldson
  github: https://github.com/wonaldson