# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            William Donaldson
tagline:          'For the love of radio.'
description:      'Innovative, music-based radio programming made to entrance
                  listeners and further radio as a creative medium.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'William Donaldson'
  url:            https://williamdonaldson.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wonaldson/wonaldson.github.io
