# Dependencies (removed)

# Permalinks
permalink:        pretty

# Setup
title:            'Wil Donaldson'
tagline:          'For the love of it.'
description:      'For the love of it.'
url:              http://wildonaldson.me
baseurl:          /

timezone:         America/New_York

author:
  name:           'Wil Donaldson'
  url:            http://wildonaldson.me

paginate:         5
paginate_path:    "posts/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wonaldson/wildonaldson.me

# Collections
collections:
 audio:
  layout: item
 code:
  layout: item
 radio:
  layout: item
 videos:
  layout: item

# Social links
social:
  facebook: https://facebook.com/wonaldson
  twitter: https://twitter.com/wonaldson
  linkedin: https://linkedin.com/in/wonaldson
  github: https://github.com/wonaldson
